name: beermonopoly
description: An app to find good beers on Vinmonopolet
publish_to: "none"
version: 2.2.6+146

environment:
  flutter: 3.41.2
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.1.1
  cached_network_image: ^3.2.3
  cronet_http: ^1.3.2
  cupertino_http: ^2.4.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  external_app_launcher: ^4.0.0
  fancy_shimmer_image: ^2.0.2
  fetch_client: ^1.1.2
  flag: ^7.0.0
  crypto: ^3.0.6
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.4
  firebase_core: ^4.2.1
  flutter_dotenv: ^6.0.0
  firebase_messaging: ^16.0.4
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  flutter:
    sdk: flutter
  flutter_fadein: ^2.0.0
  flutter_local_notifications: ^20.1.0
  geolocator: ^14.0.0
  go_router: ^17.0.0
  http: ^1.1.0
  infinite_scroll_pagination: ^5.1.1
  intl: ^0.20.0
  provider: ^6.0.2
  rate_my_app: ^2.0.0
  retry: ^3.1.0
  rotated_corner_decoration: ^2.0.0
  shared_preferences: ^2.0.12
  sqflite: ^2.0.2
  url_launcher: ^6.0.18
  path: ^1.9.1
  flutter_screenutil: ^5.9.3
  share_plus: ^12.0.1
  animated_reorderable_list: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  # integration_test:
  # sdk: flutter
  mocktail: ^1.0.1
  flutter_lints: ^6.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/icon/icon.png"
  adaptive_icon_background: "#FFA100"
  adaptive_icon_foreground: "dev_assets/icon/icon_adaptive.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
  - assets/images/placeholder.png
  - assets/images/default_avatar.png
  - assets/images/logo_transparent.png
  - .env
